version: '3.1'

services:
  db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - 5432:5432


  main_app:
    restart: always
    build: .
    image: prefix/python:3.11
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/app


volumes:
  app: