version: '3.1'

services:
  db:
    image: postgres
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
    networks:
      some_network:

  main_app:
    restart: always
    build: .
    image: prefix/python:3.11
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      some_network:

  crm_db:
    image: postgres
    env_file:
      - ./crm/.env
    ports:
      - 5433:5432
    networks:
      some_network:

  crm:
    restart: always
    build:
      context: .
      dockerfile: crm/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - crm_db
    links:
      - crm_db:crm_db
    volumes:
      - ./crm:/crm
    env_file:
      - ./crm/.env
    networks:
      some_network:
networks:
  some_network:

volumes:
  app:
  crm: