# Generated by Django 5.0.2 on 2024-02-26 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('square', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Площадь')),
                ('rooms', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Количество комнат')),
                ('floor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Этаж')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Номер')),
                ('status', models.TextField(choices=[('ON_SALE', 'Доступно к покупке'), ('SOLD', 'Продано')], max_length=255, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
