# Generated by Django 5.0.2 on 2024-03-04 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(25)], verbose_name='Номер')),
                ('color', models.TextField(validators=[django.core.validators.MaxValueValidator(225)], verbose_name='Цвет')),
                ('lighting', models.TextField(choices=[('DIODE', 'Диодное'), ('LUMINESCENT', 'Люминесцентное')], validators=[django.core.validators.MaxValueValidator(225)], verbose_name='Освещение')),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.floor'),
        ),
    ]
