# Generated by Django 5.0.2 on 2024-03-07 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_floor_alter_flat_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=255, verbose_name='Название')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Номер')),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='realty.floor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.section'),
        ),
    ]
