# Generated by Django 5.0.2 on 2024-03-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_section_alter_flat_floor_flat_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Aдрес')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('floors', models.IntegerField(verbose_name='Количество этажей')),
                ('entrances', models.IntegerField(verbose_name='Количество подъездов')),
                ('completion_date', models.DateField(verbose_name='Дата сдачи')),
                ('status', models.TextField(choices=[('COMPLETE', 'Сдан'), ('CONSTRUCTION', 'Строится')], default='COMPLETE', verbose_name='Статус')),
                ('house_type', models.TextField(choices=[('BRICK', 'Кирпичный'), ('PANEL', 'Панельный'), ('MONOLITHIC', 'Монолитный')], default='BRICK', verbose_name='Тип дома')),
            ],
            options={
                'unique_together': {('address', 'number')},
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realty.building'),
        ),
    ]
