# Generated by Django 5.0.2 on 2024-03-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
