# Generated by Django 5.0.2 on 2024-03-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_building_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
