# Generated by Django 5.0.2 on 2024-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(verbose_name='Номер телефона')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
