# Generated by Django 5.0.2 on 2024-04-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_logincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания'),
        ),
    ]
